# Generated by Django 3.2.4 on 2021-06-15 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
