dist: bionic
language: python

python:
  - '3.8'

branches:
  only:
    - staging

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

before_script:
  - cd src/

script:
  - python3 manage.py test -v2
