dist: bionic
language: python

python:
  - '3.8'

branches:
  only:
    - staging

install:
  - pip install -r requirements.txt

env:
  global:
    # we suppose the settings for Travis are in a dedicated file
    # --> travis.py in settings package
    - DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

script:
  - ./python manage.py test
