dist: bionic
language: python

python:
  - '3.8'

branches:
  only:
    - staging

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql


script:
  - python3 src/manage.py test -v2
