# Generated by Django 3.2.4 on 2021-06-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20210615_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
