# Generated by Django 3.2.4 on 2021-06-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_delete_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(
                    related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,  # noqa
                                      related_name='user_friend_list',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
