# Generated by Django 3.2.4 on 2021-06-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_auto_20210616_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-timestamp']},
        ),
    ]
