# Generated by Django 3.2.4 on 2021-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_catsitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsitter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='end',
            field=models.DateTimeField(
                null=True, verbose_name='catsitting ends'),
        ),
        migrations.AlterField(
            model_name='catsitter',
            name='start',
            field=models.DateTimeField(
                null=True, verbose_name='catsitting starts'),
        ),
    ]
