# Generated by Django 3.2.4 on 2021-06-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_start',
            field=models.DateField(null=True),
        ),
    ]
