# Generated by Django 3.2.4 on 2021-06-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='default_pet.jpg',
                upload_to=''),
        ),
    ]
