# Generated by Django 3.2.7 on 2021-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_pet_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
    ]
