# Generated by Django 3.2.7 on 2021-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_pet_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.FileField(default='default_pet.jpg', upload_to=''),
        ),
    ]
