# Generated by Django 3.2.4 on 2021-06-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20210610_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='cat',
            new_name='pet',
        ),
    ]
