# Generated by Django 3.2.4 on 2021-06-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messenger',
            options={'ordering': ['-timestamp']},
        ),
    ]
