# Generated by Django 3.2.4 on 2021-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210613_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                default='avatar_profile.jpg',
                upload_to='static/img'),
        ),
    ]
