# Generated by Django 3.2.4 on 2021-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(default='avatar_profile.jpg', path='static/img'),
        ),
    ]
