# Generated by Django 3.2.4 on 2021-06-17 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
