# Generated by Django 3.2.4 on 2021-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='uploads/avatar_picture/avatar_profile.jpg', upload_to='uploads/avatar_picture'),
        ),
    ]
